from __future__ import annotations

import argparse
import os
import sqlite3
from pathlib import Path

import psycopg
from psycopg import sql

APP_DIR = Path(__file__).resolve().parent
DEFAULT_SQLITE_PATH = APP_DIR.parent / "youke_karaoke.db"

TABLES = [
    "source_channels",
    "karaoke_candidates",
    "karaoke_songs",
    "failed_videos",
    "song_request_stats",
    "search_refresh_jobs",
]

IDENTITY_TABLES = [
    "source_channels",
    "karaoke_candidates",
    "karaoke_songs",
    "search_refresh_jobs",
]

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS source_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name TEXT NOT NULL,
    source_url TEXT NOT NULL,
    country TEXT,
    language TEXT,
    kind TEXT,
    priority INTEGER DEFAULT 0,
    last_seen_video_id TEXT,
    last_checked_at TEXT,
    is_exhausted INTEGER DEFAULT 0,
    enabled INTEGER DEFAULT 1,
    max_items INTEGER,
    refresh TEXT,
    trust TEXT
);

CREATE TABLE IF NOT EXISTS karaoke_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id TEXT,
    title TEXT,
    channel_name TEXT,
    duration INTEGER,
    thumbnail TEXT,
    source_name TEXT,
    discovered_at TEXT
);

CREATE TABLE IF NOT EXISTS karaoke_songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id TEXT UNIQUE,
    title TEXT,
    channel_name TEXT,
    thumbnail TEXT,
    duration INTEGER,
    country TEXT,
    language TEXT,
    score INTEGER,
    embed_ok INTEGER,
    source_name TEXT,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS failed_videos (
    video_id TEXT PRIMARY KEY,
    reason TEXT,
    checked_at TEXT
);

CREATE TABLE IF NOT EXISTS song_request_stats (
    video_id TEXT PRIMARY KEY,
    request_count INTEGER NOT NULL DEFAULT 0,
    last_requested_at TEXT
);

CREATE TABLE IF NOT EXISTS search_refresh_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query TEXT NOT NULL,
    normalized_query TEXT NOT NULL,
    status TEXT NOT NULL,
    requested_by_ip TEXT,
    created_at TEXT,
    finished_at TEXT,
    found_count INTEGER NOT NULL DEFAULT 0,
    error TEXT
);

CREATE INDEX IF NOT EXISTS idx_karaoke_songs_title ON karaoke_songs (title);
CREATE INDEX IF NOT EXISTS idx_karaoke_songs_channel ON karaoke_songs (channel_name);
CREATE INDEX IF NOT EXISTS idx_karaoke_songs_embed_ok ON karaoke_songs (embed_ok);
CREATE INDEX IF NOT EXISTS idx_failed_videos_video_id ON failed_videos (video_id);
CREATE INDEX IF NOT EXISTS idx_song_request_stats_last_requested ON song_request_stats (last_requested_at);
"""

ALTER_SCHEMA_SQL = """
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS source_name TEXT;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS source_url TEXT;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS language TEXT;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS kind TEXT;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS last_seen_video_id TEXT;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS last_checked_at TEXT;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS is_exhausted INTEGER DEFAULT 0;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS enabled INTEGER DEFAULT 1;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS max_items INTEGER;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS refresh TEXT;
ALTER TABLE source_channels ADD COLUMN IF NOT EXISTS trust TEXT;

ALTER TABLE karaoke_candidates ADD COLUMN IF NOT EXISTS video_id TEXT;
ALTER TABLE karaoke_candidates ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE karaoke_candidates ADD COLUMN IF NOT EXISTS channel_name TEXT;
ALTER TABLE karaoke_candidates ADD COLUMN IF NOT EXISTS duration INTEGER;
ALTER TABLE karaoke_candidates ADD COLUMN IF NOT EXISTS thumbnail TEXT;
ALTER TABLE karaoke_candidates ADD COLUMN IF NOT EXISTS source_name TEXT;
ALTER TABLE karaoke_candidates ADD COLUMN IF NOT EXISTS discovered_at TEXT;

ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS video_id TEXT;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS channel_name TEXT;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS thumbnail TEXT;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS duration INTEGER;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS language TEXT;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS score INTEGER;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS embed_ok INTEGER;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS source_name TEXT;
ALTER TABLE karaoke_songs ADD COLUMN IF NOT EXISTS created_at TEXT;

ALTER TABLE failed_videos ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE failed_videos ADD COLUMN IF NOT EXISTS checked_at TEXT;

ALTER TABLE song_request_stats ADD COLUMN IF NOT EXISTS request_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE song_request_stats ADD COLUMN IF NOT EXISTS last_requested_at TEXT;

ALTER TABLE search_refresh_jobs ADD COLUMN IF NOT EXISTS query TEXT;
ALTER TABLE search_refresh_jobs ADD COLUMN IF NOT EXISTS normalized_query TEXT;
ALTER TABLE search_refresh_jobs ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE search_refresh_jobs ADD COLUMN IF NOT EXISTS requested_by_ip TEXT;
ALTER TABLE search_refresh_jobs ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE search_refresh_jobs ADD COLUMN IF NOT EXISTS finished_at TEXT;
ALTER TABLE search_refresh_jobs ADD COLUMN IF NOT EXISTS found_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE search_refresh_jobs ADD COLUMN IF NOT EXISTS error TEXT;
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migrate YouKe SQLite data to Supabase/Postgres.")
    parser.add_argument(
        "--sqlite",
        default=os.environ.get("SQLITE_DB_PATH", str(DEFAULT_SQLITE_PATH)),
        help="Path to local SQLite DB.",
    )
    parser.add_argument(
        "--database-url",
        default=os.environ.get("SUPABASE_DB_URL") or os.environ.get("DATABASE_URL"),
        help="Supabase/Postgres connection string. Can also use SUPABASE_DB_URL or DATABASE_URL env var.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually write to Supabase. Without this flag, only prints source counts.",
    )
    parser.add_argument(
        "--truncate",
        action="store_true",
        help="Clear target tables before import. Recommended for first production import.",
    )
    parser.add_argument("--batch-size", type=int, default=1000)
    return parser.parse_args()


def get_sqlite_columns(conn: sqlite3.Connection, table: str) -> list[str]:
    rows = conn.execute(f'PRAGMA table_info("{table}")').fetchall()
    return [row[1] for row in rows]


def sqlite_table_exists(conn: sqlite3.Connection, table: str) -> bool:
    row = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
        (table,),
    ).fetchone()
    return bool(row)


def sqlite_count(conn: sqlite3.Connection, table: str) -> int:
    return int(conn.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table)).as_string(None)).fetchone()[0])


def fetch_batches(conn: sqlite3.Connection, table: str, columns: list[str], batch_size: int):
    quoted_cols = ", ".join([f'"{column}"' for column in columns])
    cursor = conn.execute(f'SELECT {quoted_cols} FROM "{table}"')
    while True:
        rows = cursor.fetchmany(batch_size)
        if not rows:
            break
        yield rows


def create_schema(pg_conn: psycopg.Connection) -> None:
    with pg_conn.cursor() as cur:
        cur.execute(SCHEMA_SQL)
        cur.execute(ALTER_SCHEMA_SQL)
    pg_conn.commit()


def truncate_target_tables(pg_conn: psycopg.Connection) -> None:
    with pg_conn.cursor() as cur:
        cur.execute(
            "TRUNCATE search_refresh_jobs, song_request_stats, failed_videos, karaoke_songs, "
            "karaoke_candidates, source_channels RESTART IDENTITY;"
        )
    pg_conn.commit()


def insert_rows(pg_conn: psycopg.Connection, table: str, columns: list[str], rows: list[tuple]) -> None:
    if not rows:
        return

    rows = normalize_rows(table, columns, rows)

    statement = sql.SQL("INSERT INTO {} ({}) VALUES ({}) ON CONFLICT DO NOTHING").format(
        sql.Identifier(table),
        sql.SQL(", ").join(sql.Identifier(column) for column in columns),
        sql.SQL(", ").join(sql.Placeholder() for _ in columns),
    )

    with pg_conn.cursor() as cur:
        cur.executemany(statement, rows)
    pg_conn.commit()


def normalize_rows(table: str, columns: list[str], rows: list[tuple]) -> list[tuple]:
    if table != "source_channels" or "is_exhausted" not in columns:
        return rows

    exhausted_idx = columns.index("is_exhausted")
    normalized = []
    for row in rows:
        values = list(row)
        if values[exhausted_idx] is not None:
            values[exhausted_idx] = bool(values[exhausted_idx])
        normalized.append(tuple(values))
    return normalized


def reset_identity_sequence(pg_conn: psycopg.Connection, table: str) -> None:
    with pg_conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                SELECT setval(
                    pg_get_serial_sequence(%s, 'id'),
                    COALESCE((SELECT MAX(id) FROM {}), 1),
                    TRUE
                )
                """
            ).format(sql.Identifier(table)),
            (table,),
        )
    pg_conn.commit()


def main() -> None:
    args = parse_args()
    sqlite_path = Path(args.sqlite)

    if not sqlite_path.exists():
        raise FileNotFoundError(f"SQLite DB not found: {sqlite_path}")

    sqlite_conn = sqlite3.connect(sqlite_path)
    try:
        available_tables = [table for table in TABLES if sqlite_table_exists(sqlite_conn, table)]
        print(f"SQLite DB: {sqlite_path}")
        print("Source counts:")
        for table in available_tables:
            print(f"  {table}: {sqlite_count(sqlite_conn, table)}")

        if not args.apply:
            print("\nDry run only. Re-run with --apply --truncate to import into Supabase.")
            return

        if not args.database_url:
            raise RuntimeError("Missing Supabase/Postgres URL. Set SUPABASE_DB_URL or DATABASE_URL.")

        with psycopg.connect(args.database_url) as pg_conn:
            create_schema(pg_conn)
            if args.truncate:
                truncate_target_tables(pg_conn)

            for table in available_tables:
                columns = get_sqlite_columns(sqlite_conn, table)
                migrated = 0
                for rows in fetch_batches(sqlite_conn, table, columns, args.batch_size):
                    insert_rows(pg_conn, table, columns, rows)
                    migrated += len(rows)
                print(f"Migrated {table}: {migrated}")

            for table in IDENTITY_TABLES:
                if table in available_tables:
                    reset_identity_sequence(pg_conn, table)

        print("Migration complete.")
    finally:
        sqlite_conn.close()


if __name__ == "__main__":
    main()
